Rminer = {
    'All': ['Change Variable Type', 'Rename Parameter', 'Change Parameter Type', 'Extract Method', 'Add Parameter', 'Merge Catch', 'Rename Attribute', 'Add Method Annotation', 'Extract Variable', 'Rename Variable', 'Add Variable Modifier', 'Rename Class', 'Change Return Type', 'Change Attribute Type', 'Add Method Modifier', 'Rename Method', 'Localize Parameter', 'Replace Pipeline With Loop', 'Parameterize Variable', 'Remove Parameter', 'Replace Anonymous With Lambda', 'Replace Loop With Pipeline', 'Add Variable Annotation', 'Change Method Access Modifier', 'Inline Method', 'Replace Attribute With Variable', 'Merge Method', 'Replace Variable With Attribute', 'Extract And Move Method', 'Move Attribute', 'Rename Package', 'Move Class', 'Extract Class', 'Move Method', 'Remove Variable Modifier', 'Extract Attribute', 'Add Attribute Modifier', 'Merge Conditional', 'Inline Variable', 'Merge Variable', 'Add Parameter Modifier', 'Remove Method Modifier', 'Extract Superclass', 'Pull Up Method', 'Pull Up Attribute', 'Move And Rename Method', 'Encapsulate Attribute', 'Split Conditional', 'Move And Rename Class', 'Change Class Access Modifier', 'Remove Attribute Modifier', 'Reorder Parameter', 'Remove Method Annotation', 'Add Class Modifier', 'Remove Parameter Annotation', 'Move Source Folder', 'Remove Class Modifier', 'Change Attribute Access Modifier', 'Merge Class', 'Split Class', 'Move Code', 'Merge Parameter', 'Merge Attribute', 'Remove Thrown Exception Type', 'Move And Inline Method', 'Extract Interface', 'Add Thrown Exception Type', 'Invert Condition', 'Parameterize Attribute', 'Change Type Declaration Kind', 'Extract Subclass', 'Push Down Method', 'Push Down Attribute', 'Remove Parameter Modifier', 'Split Parameter', 'Change Thrown Exception Type', 'Split Attribute', 'Split Variable', 'Modify Method Annotation', 'Remove Variable Annotation', 'Add Attribute Annotation', 'Replace Attribute', 'Add Class Annotation', 'Inline Attribute', 'Remove Attribute Annotation', 'Collapse Hierarchy', 'Remove Class Annotation', 'Move And Rename Attribute', 'Modify Attribute Annotation', 'Move Package', 'Add Parameter Annotation', 'Split Method', 'Split Package', 'Merge Package', 'Modify Parameter Annotation', 'Modify Class Annotation', 'Replace Anonymous With Class', 'Modify Variable Annotation', 'Assert Throws', 'Parameterize Test'],
    'Package': [
        'Move Package',
        'Split Package',
        'Merge Package',
        'Rename Package'
    ],
    'Class': [
        'Rename Class',
        'Change Class Access Modifier',
        'Add Class Modifier',
        'Remove Class Modifier',
        'Merge Class',
        'Split Class',
        'Move Class',
        'Extract Class',
        'Move And Rename Class',
        'Collapse Hierarchy',
        'Remove Class Annotation',
        'Add Class Annotation',
        'Modify Class Annotation',
        'Replace Anonymous With Class',
        'Extract Superclass',
        'Pull Up Attribute',
        'Change Attribute Access Modifier',
        'Extract Subclass',
        'Push Down Attribute',
        'Push Down Method',
        'Change Type Declaration Kind',
        'Rename Attribute',
        'Change Attribute Type',
        'Localize Parameter',
        'Replace Anonymous With Lambda',
        'Extract Attribute',
        'Add Attribute Modifier',
        'Replace Attribute With Variable',
        'Move Attribute',
        'Extract Interface',
        'Encapsulate Attribute',
        'Add Attribute Annotation',
        'Replace Attribute',
        'Inline Attribute',
        'Remove Attribute Annotation',
        'Remove Attribute Modifier',
        'Modify Attribute Annotation',
        'Parameterize Attribute',
        'Split Attribute',
        'Merge Attribute',
        'Move And Rename Attribute'
    ],
    'Test': [
        'Assert Throws',
        'Parameterize Test'
    ],
    'Method': [
        'Extract Method',
        'Add Method Annotation',
        'Rename Method',
        'Remove Method Annotation',
        'Change Method Access Modifier',
        'Inline Method',
        'Merge Method',
        'Move Method',
        'Extract And Move Method',
        'Remove Method Modifier',
        'Pull Up Method',
        'Move And Rename Method',
        'Remove Thrown Exception Type',
        'Move And Inline Method',
        'Modify Method Annotation',
        'Split Method',
        'Merge Catch',
        'Add Parameter Modifier',
        'Reorder Parameter',
        'Remove Parameter Annotation',
        'Add Thrown Exception Type',
        'Remove Parameter Modifier',
        'Change Thrown Exception Type',
        'Modify Parameter Annotation',
        'Rename Parameter',
        'Change Parameter Type',
        'Add Parameter',
        'Add Method Modifier',
        'Change Return Type',
        'Remove Parameter',
        'Parameterize Variable',
        'Add Parameter Annotation',
        'Merge Parameter',
        'Split Parameter',
    ],
    'Organization': [
        'Merge Conditional',
        'Split Conditional',
        'Move Code',
        'Invert Condition',
        'Replace Loop With Pipeline',
        'Replace Pipeline With Loop',
        'Move Source Folder'
    ],
    'Variable': [
        'Change Variable Type',
        'Extract Variable',
        'Rename Variable',
        'Add Variable Modifier',
        'Add Variable Annotation',
        'Remove Variable Modifier',
        'Remove Variable Annotation',
        'Modify Variable Annotation',
        'Replace Variable With Attribute',
        'Inline Variable',
        'Merge Variable',
        'Split Variable',
    ]
}
metrics = {
    'complexity': [
        "AvgCyclomatic",
        "Cyclomatic",
        "MaxCyclomatic",
        "SumCyclomatic",
        "MaxNesting"
    ],
    'coupling': [
        "CountClassBase",
        "CountClassCoupled",
        "CountClassCoupledModified",
        "CountClassDerived",
        "CountInput",
        "CountOutput"
    ],
    'cohesion': [
        "PercentLackOfCohesion",
        "PercentLackOfCohesionModified"
    ]
}